import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { StartMockWorker } from '@/mocks/mockServer';

import Footer from '@/components/footer';
import Header from '@/components/header';
import ThemeWrapper from '@/components/themeWrapper';
import { Container } from '@mui/material';

const robotoSans = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${robotoSans.variable} ${robotoMono.variable}`}>
      <body>
        <StartMockWorker>
          <ThemeWrapper>
            <Header/>
            <Container className="page-margin" maxWidth={ false } sx={{ maxWidth:'1080px' }}>
              {children}
            </Container>
            <Footer />
          </ThemeWrapper>
        </StartMockWorker>
      </body>
    </html>
  );
}
